global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'server'
    metrics_path: '/_metrics'
    static_configs:
      - targets: ['server:8080']

  - job_name: 'client'
    metrics_path: '/_metrics'
    static_configs:
      - targets: ['client:8080']